services:
  web:
    build: .
    container_name: webscraper-django
    working_dir: /app/webscraper/webscraper_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always

  cron:
    build: .
    container_name: webscraper-cron
    working_dir: /app/webscraper/webscraper_project
    command: cron -f
    volumes:
      - .:/app
    restart: always
